#ifndef PARAMS_H
#define PARAMS_H

#define AKCN_K 3

#define AKCN_N 256
#define AKCN_Q 7681

#define AKCN_ETA 2

#define AKCN_SYMBYTES 32   /* size in bytes of shared key, hashes, and seeds */

#define AKCN_POLYBYTES              416
#define AKCN_POLYCOMPRESSEDBYTES    96
#define AKCN_POLYVECBYTES           (AKCN_K * AKCN_POLYBYTES)
#define AKCN_POLYVECCOMPRESSEDBYTES (AKCN_K * 320)

#define AKCN_INDCPA_MSGBYTES       AKCN_SYMBYTES
#define AKCN_INDCPA_PUBLICKEYBYTES (AKCN_POLYVECCOMPRESSEDBYTES + AKCN_SYMBYTES)
#define AKCN_INDCPA_SECRETKEYBYTES (AKCN_POLYVECBYTES)
#define AKCN_INDCPA_BYTES          (AKCN_POLYVECCOMPRESSEDBYTES + AKCN_POLYCOMPRESSEDBYTES)

#define AKCN_PUBLICKEYBYTES  (AKCN_INDCPA_PUBLICKEYBYTES)
#define AKCN_SECRETKEYBYTES  (AKCN_INDCPA_SECRETKEYBYTES +  AKCN_INDCPA_PUBLICKEYBYTES + 2*AKCN_SYMBYTES) /* 32 bytes of additional space to save H(pk) */
#define AKCN_CIPHERTEXTBYTES  AKCN_INDCPA_BYTES

#endif
